### ISSUE TITLE
Support certificate authentication

### ISSUE THREAD

**Issue by hannesm** [anmonteiro/gluten#23]
At the moment, in `lwt-unix/tls_io_real.ml` a `null_auth` that always returns success is provided. This opens the path for any person-in-the-middle attack. It would be nice to use e.g. [ca-certs](https://github.com/mirage/ca-certs) to authenticate the server certificate (ca-certs uses the system CA file to achieve this).

For gluten-mirage, I am not entirely sure about the code, but it looks like conduit-mirage is used which use ca certificates via the [ca-certs-nss](https://github.com/mirage/ca-certs-nss) package.

**Comment by anmonteiro** [comment]
#24 said this does _not_ fix it. bad bot.

**Comment by hannesm** [comment]
..but in the end, I don't really care too much about this. and closing this issue.
