### ISSUE TITLE
New release of gluten packages

### ISSUE THREAD

**Issue by tmcgilchrist** [anmonteiro/gluten#72]
@anmonteiro Would it be possible to get a new `gluten-eio` release that includes the eio v0.12 changes?
I've created https://github.com/anmonteiro/gluten/pull/71 to update the changelog. Let me know if I can help in any other way.

**Comment by anmonteiro** [comment]
Absolutely. Doing that today (and thanks for #71!)

**Comment by anmonteiro** [comment]
0.5 released 

166e1e917710e1e43b04d33a368b6701a9f8b1f5

https://github.com/anmonteiro/gluten/releases/tag/0.5.0

https://github.com/ocaml/opam-repository/pull/24676
